### ISSUE TITLE
Local Developer Experience - Run multiple dapr apps using `dapr run -f`

### ISSUE THREAD

**Issue by shubham1172** [dapr/cli#1123]
## Describe proposal

This is related to the implementation of the proposal https://github.com/dapr/proposals/blob/main/0003-I-enhance-dapr-run-multiple-apps.md

### Targets for v1.10
The main requirements for the command:
- being able to configure multiple dapr apps from a single configuration file
- users should be able to use normal dapr CLI commands for self hosted mode against any apps that are started through `dapr run -f`

- Initial implementation will only support Linux & macOs.
- `dapr run -f <path>` will be an interactive process running completely for the lifecycle of applications, on exiting the process, 
- all other spawned processes will also quit.
- logs will be written to a predefined location. Users will need to manually tail the file. 

- [x] Get Sign off on feature proposal dapr/proposals#6
- [x] https://github.com/dapr/cli/issues/1141
- [x] https://github.com/dapr/cli/issues/1142
- [x] https://github.com/dapr/cli/issues/1143
- [x] Docs for `dapr run -f`
- [x] https://github.com/dapr/cli/issues/1153

Future enhancements
- [ ] https://github.com/dapr/cli/issues/1220
- [ ] https://github.com/dapr/cli/issues/1221
- [ ] https://github.com/dapr/cli/issues/1228
- [ ] https://github.com/dapr/cli/issues/1204
- [ ] https://github.com/dapr/cli/issues/1144
- [ ] https://github.com/dapr/cli/issues/1145
- [ ] https://github.com/dapr/cli/issues/1146
- [ ] https://github.com/dapr/cli/issues/1147
- [ ] https://github.com/dapr/cli/issues/1154
- [ ] https://github.com/dapr/cli/issues/1155

## ~~Describe the proposal (Old version)~~

This issue derives from https://github.com/dapr/community/issues/207 to propose two new commands - 
`dapr compose up` and `dapr compose down`.

### Compose file structure

```yaml
version: 1
common:
  environment:  # any environment variable shared among apps
    - DEBUG: true
services:
  - id: kafka
    image: docker.io/bitnami/kafka
    port: 4040
    environment:
      - KAFKA_BROKER_ID: 1
apps:
  - id: webapp
    root_directory: ./webapp/
    components_directory: ./webapp/components # can be default by convention too, ignore if dir is not found.
    config_file: ./webapp/config.yaml # can be default by convention too, ignore if file is not found.
    protocol: HTTP
    port: 8080
    command: python3 app.py
  - id: backend
    root_directory: ./backend/
    components_directory: ./backend/components # can be default by convention too, ignore if dir is not found.
    config_file: ./backend/config.yaml # can be default by convention too, ignore if file is not found.
    protocol: GRPC
    port: 3000
    env:
      - DEBUG: false
    command: ./backend
```

### User experience

- The user can run `dapr compose up` to start these services and apps
- If something crashes, it will be restarted with exponential back-off until a back-off limit
- If ports are missing, compose automatically finds a free port
- The user can run `dapr compose down` to gracefully stop everything

### Open questions

1. Should we separate `services` into another proposal?
1. Should we support running apps in containers directly?
1. Should we support running alternate container runtime (like podman) since CLI already does that?

## Release Note

RELEASE NOTE: **ADD** Dapr compose up and down
