### ISSUE TITLE
Create a template for configuring multiple applications to be run with `dapr run` command

### ISSUE THREAD

**Issue by mukundansundar** [dapr/cli#1141]
## Describe the proposal
As part of implementing dapr/proposals#6: 
- create a template based on seen in the proposal. 
- Implement YAML template processing with UTs for the run configuration file.

Example 
```yaml

version: 1

common: (optional)

  resources_dir: ./app/components # any dapr resources to be shared across apps

  env:  # any environment variable shared among apps

    - DEBUG: true

apps:

  - app_id: webapp ## required

    app_dir: ./webapp/ ## required

    resources_dir: ./webapp/components # (optional) can be default by convention too, ignore if dir is not found.

    config_file: ./webapp/config.yaml # (optional) can be default by convention too, ignore if file is not found.

    app_protocol: HTTP

    app_port: 8080

    app_health_check_path: "/healthz" # All _ converted to - for all properties defined under daprd section

    command: ["python3" "app.py"]

  - app_id: backend

    app_dir: ./backend/

    app_protocol: GRPC

    app_port: 3000

    unix_domain_socket: "/tmp/test-socket"

    env:

      - DEBUG: false

    command: ["./backend"]

```
A single run configuration file contains a single YAML definition. 

Minimum validations to be done :
- YAML struct is correct
- required fileds are there
- paths are reachable and already there

related to #1123 

## Release Note

RELEASE NOTE:
