### ISSUE TITLE
Add capability to run multiple apps from a given run configuration file

### ISSUE THREAD

**Issue by mukundansundar** [dapr/cli#1143]
## Describe the proposal
Following proposal dapr/proposals#6, implement basic dapr run -f with E2Es.
- run app commands and daprd command, if app command is not given run only daprd. 
- Generate the ports automatically and inject as env var into app (HTTP, GRPC, Internal GRPC and Metrics). 
- Write logs to file and STDOUT See `io.MultiWriter`
- Run apps sequentially

Potential output when the below config file is run is shown.

Consider `pwd -> ~/workspace/apps/`

```yaml

version: 1

common: (optional)

  resources_dir: ./app/components # any dapr resources to be shared across apps

  env:  # any environment variable shared among apps

    - DEBUG: true

apps:

  - app_id: webapp ## required

    app_dir: ./webapp/ ## required

    resources_dir: ./webapp/components # (optional) can be default by convention too, ignore if dir is not found.

    config_file: ./webapp/config.yaml # (optional) can be default by convention too, ignore if file is not found.

    app_protocol: HTTP

    app_port: 8080

    app_health_check_path: "/healthz" # All _ converted to - for all properties defined under daprd section

    command: ["python3" "app.py"]

  - app_id: backend

    app_dir: ./backend/

    app_protocol: GRPC

    app_port: 3000

    unix_domain_socket: "/tmp/test-socket"

    env:

      - DEBUG: false

    command: ["./backend"]

```

Example output :

```bash

$ dapr run -f ./dapr.yaml



Validated run confiugration file : "./dapr.yaml"

Contains applications : "webapp", "backend"

Common Resources directory : "./apps/components"

No common configuration file given

Common env vars : DEBUG, (list keys)



<webapp> Resolving resources dir:

<webapp> Checking for `.dapr` folder in "./webapp" ... NOT FOUND

<webapp> Using common resources directory "./apps/components"



<webapp> Resolving config file:

<webapp> Checking for `.dapr` folder in "./webapp" ... NOT FOUND

<webapp> No common configuration file given

<webapp> Checking for `.dapr` folder in "~/" ... FOUND

<webapp> Checking for `~/.dapr/config.yaml` ... FOUND

<webapp> Using `~/.dapr/config.yaml` for configuration file



<backend> Resolving resources dir:

<backend> Checking for `.dapr` folder in "./backend" ... FOUND

<backend> Using resources directory "./backend/.dapr/components"



<backend> Resolving config file:

<backend> Checking for `.dapr` folder in "./backend" ... FOUND

<backend> Checking for `./.dapr/config.yaml` for "backend" ... FOUND

<backend> Using `./.dapr/config.yaml` for configuration file



Generated Run ID : <uuid>



Starting App "webapp" and associated daprd process

<webapp> DAPR_HTTP_PORT 3600, DAPR_GRPC_PORT 51020, DAPR_METRICS_PORT 9990

<webapp> Started daprd process successfully (Check for `Status Running log`)

<webapp> Writing app logs to ./webapp/.dapr/logs/app_uuid.log

<webapp> Writing daprd logs to ./webapp/.dapr/logs/daprd_uuid.log




Starting App "backend" and associated daprd process

<backend> DAPR_HTTP_PORT 3602, DAPR_GRPC_PORT 51010, DAPR_METRICS_PORT 9993

<backend> Started daprd process successfully (Check for `Status Running log`)

<backend> Writing app logs to ./backend/.dapr/logs/app_uuid.log

<backend> Writing daprd logs to ./backend/.dapr/logs/daprd_uuid.log



CTRL + C



Stopping <webbapp>

Stopping <backend>

```

related to #1123 

## Release Note

RELEASE NOTE:
