### ISSUE TITLE
[Proposal] Add metadata field for applications in Dapr Compose configuration file 

### ISSUE THREAD

**Issue by philliphoff** [dapr/cli#1154]
## Describe the proposal

This proposal is related to the [Dapr Compose](https://github.com/dapr/cli/issues/1123) feature work currently underway.

Each application defined in the Dapr Compose configuration file has a command property that is run by Dapr.  The command is arbitrary and Dapr has (and requires) no context around that command.  Tooling, however, often needs to know more in order to provide capabilities unique to the application that the command represents.  For example, in order for tooling to attach a debugger to the process started via that command, it may need to know the application's development platform (e.g. whether Node, Java, Python, or .NET) or have a pointer to the platform-specific configuration file (e.g. the .NET `.csproj` file).  While the development platform can sometimes be inferred from the command (e.g. `node main.js` or `dotnet run`), commands are often pointers to scripts which obscure the underlying launch mechanism.  Some information may also be inferred from pointers to the application's root directory, but there are a number of scenarios where that is still not enough to be certain about an application's structure.

I propose that the Dapr Compose configuration file format allow arbitrary metadata to be associated with each application.  At a minimum, this metadata should be in the form of key-value pairs but, if reasonably possible, more structured metadata would be ideal.  This metadata section would allow developers a place to provide hints to tooling about the application, such as the development platform and a pointer to its configuration file.  This optional metadata could be defined by the tooling and need not be interpreted by the Dapr Compose feature itself--in fact, should probably ignore it altogether. If and when such metadata becomes useful to Dapr itself, it could always be "promoted" to part of the configuration file schema.

With this proposal, the developer now has a single place to define the application model, reducing the chance for duplicate configuration to get out of sync, accessible to both Dapr itself as well as any Dapr-related tooling, but without necessarily tightly coupling the two together, or requiring Dapr to comprehend tooling-specific concerns.

For example, the addition of a `metadata` property in each application section:

```yaml
version: 1
common:
  environment:  # any environment variable shared among apps
    - DEBUG: true
services:
  - id: kafka
    image: docker.io/bitnami/kafka
    port: 4040
    environment:
      - KAFKA_BROKER_ID: 1
apps:
  - id: webapp
    root_directory: ./webapp/
    components_directory: ./webapp/components
    config_file: ./webapp/config.yaml 
    protocol: HTTP
    port: 8080
    command: python3 app.py
    metadata:
      - name: x-platform-type # Could technically be inferred, but still useful for consistency across applications.
        value: python                     
      - name: x-python-framework  # Some Python frameworks have well-known (but different) ports for debugging.
        value: flask                         
  - id: backend
    root_directory: ./backend/
    components_directory: ./backend/components
    config_file: ./backend/config.yaml
    protocol: GRPC
    port: 3000
    env:
      - DEBUG: false
    command: ./backend
    metadata:
      - name: x-platform-type # Can't be inferred from the command as it's obscured via script
        value: dotnet
      - name: x-dotnet-project # Several project files, with varying extensions, might exist within the root
        value: ./backend/backend.csproj
```

## Release Note

RELEASE NOTE:
