### ISSUE TITLE
[Proposal] Add root `name` property to run file

### ISSUE THREAD

**Issue by philliphoff** [dapr/cli#1204]
## Describe the proposal

For tooling that displays sets of running Dapr applications orchestrated by run files, there's the question of how to label the group.  The name of the run file will (by convention) be the same (i.e. `dapr.yaml`), so that's not really an option.  Using the name of the folder in which the run file resides is a reasonable default, but it can easily be unhelpful if that folder is common or otherwise not meaningful (e.g. `src`).

There should be an optional property in the run file that allows developers to give the "run" an explicit name that is more useful to the developer than any that the CLI or tooling might infer.  This property need not be used by the CLI itself; it exists strictly for tooling that needs to manage multiple run files.

```yaml
version: 1
name: "Dapr Pub-Sub Tutorial" # <-- The proposed, optional `name` property.
apps:
  - appDirPath: ./csharp-subscriber/
    appPort: 5009
    command: ["dotnet", "run", "csharp-subscriber.csproj"]
  - appDirPath: ./node-subscriber/
    appPort: 3000
    command: ["node", "app.js"]
  - appDirPath: ./python-subscriber/
    appPort: 5001
    command: ["python3", "app.py"]
  - appDirPath: ./react-form/
    appPort: 8080
    command: ["npm", "run", "start"]
```

While `name` seems like a pretty standard property for such files, as an alternative, there could be a common metadata dictionary added to the root of the schema, where the developer could add values not directly used by the CLI or Dapr runtime, similar to #1154 but at the root.  This would allow tooling to define arbitrary properties it cares about without requiring the CLI to constantly change its schema.

## Release Note

RELEASE NOTE:

**Comment by mukundansundar** [comment]
>While name seems like a pretty standard property for such files, as an alternative, there could be a common metadata dictionary added to the root of the schema, where the developer could add values not directly used by the CLI or Dapr runtime, similar to https://github.com/dapr/cli/issues/1154 but at the root. This would allow tooling to define arbitrary properties it cares about without requiring the CLI to constantly change its schema.

@philliphoff Could you explain what type of properties that you expect to see in the `metadata` root map, if one such field was added?

**Comment by philliphoff** [comment]
> Could you explain what type of properties that you expect to see in the metadata root map, if one such field was added?

@mukundansundar A metadata property would be a place for arbitrary tooling-specific values like the run's name (as mentioned above), or perhaps a central entry point (for browsing from tooling), etc.  Maybe what version of Dapr the run requires (e.g. because of the use of certain components)?  I imagine it would be for things that are intrinsic to the run/applications such that it wouldn't make sense to store those properties in a different place, but the advantage being that the "official" schema of the run file need not change for every value that enables some tool (not Dapr itself) to do something interesting.

```yaml

version: 1
metadata: # <-- The proposed alternative, an optional `metadata` property.
 - name: runName
   value:  "Dapr Pub-Sub Tutorial"
 - name: entryPoint
   value: "http://localhost:8080"
 - name: daprRuntimeVersion
   value: "1.9.x"
apps:
  - appDirPath: ./csharp-subscriber/
    appPort: 5009
    command: ["dotnet", "run", "csharp-subscriber.csproj"]
  - appDirPath: ./node-subscriber/
    appPort: 3000
    command: ["node", "app.js"]
  - appDirPath: ./python-subscriber/
    appPort: 5001
    command: ["python3", "app.py"]
  - appDirPath: ./react-form/
    appPort: 8080
    command: ["npm", "run", "start"]
```
