### ISSUE TITLE
dapr run with resourcesPath: ~/some/folder  doesn't resolve ~ to the user's home folder

### ISSUE THREAD

**Issue by sethwenzel** [dapr/cli#1245]
## Expected Behavior

```yaml
version: 1
common:
  resourcesPath: ~/some/external/folder/path
apps:
  ....
```

should look for the components folder under the user's home folder -- `/home/<user>/some/external/folder/path`

## Actual Behavior

`resourcesPath: ~/some/folder` will cause the error:

> ❌  Error getting apps from config file: error in getting the file info for /home/\<user\>/projects/dapr-project/\~/some/folder: stat /home/\<user\>/projects/dapr-project/\~/some/folder: no such file or directory

## Steps to Reproduce the Problem

use "~" in the `resourcesPath` in a dapr.yaml file

## Release Note

RELEASE NOTE:
