### ISSUE TITLE
Multi App Run: Move log destination fields for daprd and apps to common section

### ISSUE THREAD

**Issue by pravinpushkar** [dapr/cli#1293]
## Expected Behavior

I should be able to put `daprdLogDestination` and `appLogDestination` in the common section like below - 

```yaml
version: 1
common:
  daprdLogDestination: file
  appLogDestination: file
apps:
```
## Actual Behavior
Currently I can only specify in the app's section - 

```yaml
version: 1
common:
apps:
 - appID: frontendapp
   daprdLogDestination: file
   appLogDestination: file 
```

## Release Note

RELEASE NOTE:
