### ISSUE TITLE
Dapr CLI Docker Container

### ISSUE THREAD

**Issue by mindovermiles262** [dapr/cli#1340]
## Describe the proposal

Dapr should provide a container which contains the dapr cli preinstalled on it. A usecase may be when you want to run a kuberentes job using Dapr CLI:

```
apiVersion: batch/v1
kind: Job
metadata:
  name: dapr-cli
spec:
  template:
    spec:
      containers:
      - name: dapr-cli
        image: daprio/cli
        command: ["dapr", "..."]
```

As discussed in https://github.com/dapr/cli/pull/1339 this Issue is for determining if there is enough interest in Dapr creating and supporting a Github action pipeline and docker container.

## Release Note

RELEASE NOTE: **FEATURE** Creates new Workflow to publish Dapr CLI to Docker Hub
