### ISSUE TITLE
components command does not show cron binding

### ISSUE THREAD

**Issue by mckageth000** [dapr/cli#1372]
## Expected Behavior

When I run `dapr components` with the appropriate flags, I should see a cron input binding component that I have configured.

## Actual Behavior

When I run `dapr components` with the appropriate flags, I do not see the cron input binding component that I have configured.

## Steps to Reproduce the Problem

- Add a cron input binding to your project. Here is essentially what my config for my binding looks like:
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: my-binding
  namespace: my-namespace
spec:
  type: bindings.cron
  version: v1
  metadata:
    - name: schedule
      value: "@every 10s"
    - name: direction
      value: "input"

```
- Run `dapr run` with the flags you need for your project
  - be sure to add a `--resources-path <binding-config-dir>` flag to your run command to tell dapr where your binding config is
- Observe that your cron binding is working as expected
- In another terminal, run `dapr components -k -A`
- Observe that your cron binding is not listed as a component

(optional:)
- Copy your binding config file to the same place that the default components live (in my case, `~/.dapr/components`
- Restart your project
- Observe that the component is now listed when the `dapr components ...` command is run

## Release Note

RELEASE NOTE:
