### ISSUE TITLE
Update the holopin.yaml to use the cli badge

### ISSUE THREAD

**Issue by marcduiker** [dapr/cli#1398]
Update the `.github/holopin.yaml` file with the following info to set the default [Holopin badge](https://www.holopin.io/sticker/clutq4bgp107990fl1h4m7jp3b) for this repo:

```yaml
organization: dapr
defaultSticker: clutq4bgp107990fl1h4m7jp3b
stickers:
  -
    id: clutq4bgp107990fl1h4m7jp3b
    alias: cli-badge
```

Once this is in place, maintainers can award contributors via the Holopin Bot by mentioning the contributors' username in a PR comment when the PR is accepted: `@holopin-bot @username`

---
Please label this as a *good first issue*.
