### ISSUE TITLE
dapr init - dapr_redis: Bind for 0.0.0.0:6379 failed: port is already in allocated.

### ISSUE THREAD

**Issue by frenchyjef** [dapr/cli#346]
## Expected Behavior

I am currently developing multiple applications (unrelated to dapr) on my local computer which are all already using the same Redis Docker container instance on port 6379.

When running `dapr init`, dapr should discover that Redis is already running at port 6379 and reuse that same instance.

## Actual Behavior

When running `dapr init` in a Command Prompt (Run as Administrator), I get the following error:
```
C:\Windows\system32>dapr init
Making the jump to hyperspace...
WARNING: could not delete run data file
Downloading binaries and setting up components...
docker: Error response from daemon: driver failed programming external connectivity on endpoint dapr_redis (c2c3a50964154d0e10de7714244868414b0d87d7012ce174395d681a7ed6fb50): Bind for 0.0.0.0:6379 failed: port is already allocated.
```

After reading through the configuration instructions, I created a folder named components in the root folder of the dapr.exe and then created a file named redis.yaml with the following content hoping it would discover and attach to the existing Redis container but still getting the same error.

```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  metadata:
  - name: redisHost
    value: rediscache:6379    

```
## Steps to Reproduce the Problem

Download and run Docker for Windows (Linux Containers).
Download and run a Docker instance of Redis on your local computer and use port 6379.
Run `dapr init`

**Comment by yaron2** [comment]
Can you change rediscache:6379 to localhost:6379?

**Comment by frenchyjef** [comment]
C:\dapr\components\redis.yaml
```
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
spec:
  type: state.redis
  metadata:
  - name: redisHost
    value: localhost:6379
```
Command Prompt (Run as Administrator)
```
C:\Windows\system32>dapr init
Making the jump to hyperspace...
WARNING: could not delete run data file
Downloading binaries and setting up components...
docker: Error response from daemon: driver failed programming external connectivity on endpoint dapr_redis (c734108e70aa80d8bff644847e364ed4bbb44b804f14931d30589f839c792912): Bind for 0.0.0.0:6379 failed: port is already allocated.

```
